'use client';
import { useEffect, useMemo, useState } from 'react';
import { tryCreateSupabaseBrowserClient } from '@/lib/supabase/client';

async function token(){ const s=tryCreateSupabaseBrowserClient(); if(!s) return null; const {data:{session}}=await s.auth.getSession(); return session?.access_token??null; }

export function MemberSurveys(){
  const [surveys,setSurveys]=useState<any[]>([]); const [questions,setQuestions]=useState<any[]>([]); const [active,setActive]=useState(''); const [answers,setAnswers]=useState<Record<string,any>>({}); const [notice,setNotice]=useState('');
  const [loading, setLoading] = useState(true);
  useEffect(()=>{ void (async()=>{ const t=await token(); const res=await fetch('/api/member/surveys',{headers:t?{Authorization:`Bearer ${t}`}:{}}); const j=await res.json(); setSurveys(j.surveys??[]); setQuestions(j.questions??[]); setActive(j.surveys?.[0]?.id??''); setLoading(false); })(); },[]);
  const qs=useMemo(()=>questions.filter((q)=>q.survey_id===active),[questions,active]);
  async function submit(){ const t=await token(); const payload={survey_id:active,answers:qs.map((q:any)=>({question_id:q.id,answer_text:q.question_type==='text'?answers[q.id]??null:null,answer_number:q.question_type==='number'?Number(answers[q.id]):null,answer_yes_no:q.question_type==='yes_no'?answers[q.id]===true:null,answer_choice:q.question_type==='choice'?answers[q.id]??null:null}))}; const res=await fetch('/api/member/surveys',{method:'POST',headers:{'Content-Type':'application/json',...(t?{Authorization:`Bearer ${t}`}:{})},body:JSON.stringify(payload)}); setNotice(res.ok?'ส่งคำตอบแล้ว':'ส่งไม่สำเร็จ'); }
  if (loading) return <div style={{padding:16,maxWidth:520,margin:'0 auto'}}><div className="kaona-card"><p style={{margin:0}}>กำลังโหลดแบบสำรวจ…</p></div></div>;
  if (surveys.length === 0) return <div style={{padding:16,maxWidth:520,margin:'0 auto'}}><div className="kaona-card"><p style={{margin:0,fontWeight:700}}>📝 ยังไม่มีแบบสำรวจ</p><p style={{margin:'4px 0 0',fontSize:13,color:'#6b7280'}}>เมื่อมีแบบสำรวจใหม่ ระบบจะแสดงในหน้านี้</p></div></div>;
  return <div style={{padding:16,maxWidth:520,margin:'0 auto',display:'grid',gap:12}}><h2 style={{margin:'0 0 2px',fontSize:22,lineHeight:1.35}}>แบบสำรวจภาคสนาม</h2><select className='admin-select' value={active} onChange={e=>setActive(e.target.value)}>{surveys.map((s)=><option key={s.id} value={s.id}>{s.title}</option>)}</select>{qs.length===0&&<div className='kaona-card'><p style={{margin:0,fontSize:13,color:'#6b7280'}}>ไม่มีคำถามในแบบสำรวจนี้</p></div>}{qs.map((q:any)=><div key={q.id} className='kaona-card' style={{marginTop:2}}><p style={{margin:0,lineHeight:1.6,overflowWrap:'anywhere'}}>{q.question_text}</p>{q.question_type==='text'&&<input className='admin-input' onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} />} {q.question_type==='number'&&<input type='number' className='admin-input' onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} />} {q.question_type==='yes_no'&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className='admin-btn' style={{minHeight:40,padding:'8px 14px'}} onClick={()=>setAnswers(a=>({...a,[q.id]:true}))}>ใช่</button><button className='admin-btn' style={{minHeight:40,padding:'8px 14px'}} onClick={()=>setAnswers(a=>({...a,[q.id]:false}))}>ไม่ใช่</button></div>} {q.question_type==='choice'&&<select className='admin-select' onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))}><option value=''>เลือก</option>{(q.choices??[]).map((c:string)=><option key={c} value={c}>{c}</option>)}</select>}</div>)}<button className='admin-btn admin-btn--primary' style={{minHeight:44}} onClick={()=>void submit()} disabled={!active}>ส่งคำตอบ</button>{notice&&<p style={{margin:0,fontWeight:600}}>{notice}</p>}</div>
}
