'use client';
import { useEffect, useMemo, useState } from 'react';
import { tryCreateSupabaseBrowserClient } from '@/lib/supabase/client';

async function token(){ const s=tryCreateSupabaseBrowserClient(); if(!s) return null; const {data:{session}}=await s.auth.getSession(); return session?.access_token??null; }

export function MemberSurveys(){
  const [surveys,setSurveys]=useState<any[]>([]); const [questions,setQuestions]=useState<any[]>([]); const [active,setActive]=useState(''); const [answers,setAnswers]=useState<Record<string,any>>({}); const [notice,setNotice]=useState('');
  useEffect(()=>{ void (async()=>{ const t=await token(); const res=await fetch('/api/member/surveys',{headers:t?{Authorization:`Bearer ${t}`}:{}}); const j=await res.json(); setSurveys(j.surveys??[]); setQuestions(j.questions??[]); setActive(j.surveys?.[0]?.id??''); })(); },[]);
  const qs=useMemo(()=>questions.filter((q)=>q.survey_id===active),[questions,active]);
  async function submit(){ const t=await token(); const payload={survey_id:active,answers:qs.map((q:any)=>({question_id:q.id,answer_text:q.question_type==='text'?answers[q.id]??null:null,answer_number:q.question_type==='number'?Number(answers[q.id]):null,answer_yes_no:q.question_type==='yes_no'?answers[q.id]===true:null,answer_choice:q.question_type==='choice'?answers[q.id]??null:null}))}; const res=await fetch('/api/member/surveys',{method:'POST',headers:{'Content-Type':'application/json',...(t?{Authorization:`Bearer ${t}`}:{})},body:JSON.stringify(payload)}); setNotice(res.ok?'ส่งคำตอบแล้ว':'ส่งไม่สำเร็จ'); }
  return <div style={{padding:16,maxWidth:520,margin:'0 auto'}}><h2>แบบสำรวจภาคสนาม</h2><select className='admin-select' value={active} onChange={e=>setActive(e.target.value)}>{surveys.map((s)=><option key={s.id} value={s.id}>{s.title}</option>)}</select>{qs.map((q:any)=><div key={q.id} className='kaona-card' style={{marginTop:10}}><p>{q.question_text}</p>{q.question_type==='text'&&<input className='admin-input' onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} />} {q.question_type==='number'&&<input type='number' className='admin-input' onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} />} {q.question_type==='yes_no'&&<div><button className='admin-btn' onClick={()=>setAnswers(a=>({...a,[q.id]:true}))}>ใช่</button><button className='admin-btn' onClick={()=>setAnswers(a=>({...a,[q.id]:false}))}>ไม่ใช่</button></div>} {q.question_type==='choice'&&<select className='admin-select' onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))}><option value=''>เลือก</option>{(q.choices??[]).map((c:string)=><option key={c} value={c}>{c}</option>)}</select>}</div>)}<button className='admin-btn admin-btn--primary' onClick={()=>void submit()} disabled={!active}>ส่งคำตอบ</button>{notice&&<p>{notice}</p>}</div>
}
