import { NextResponse } from 'next/server';
import { createServerSupabaseClient } from '../../auth/line/line-auth-helpers';
import { requireAdminPermission, isForbidden } from '../../admin/members/_admin-auth';
import { calculateIntake } from '@/lib/intake/calculate-intake';
import { findOrCreateBooking, resolveMemberId } from '@/lib/intake/find-booking';
import { sendIntakeReceipt } from '@/lib/intake/send-intake-receipt';
export const dynamic = 'force-dynamic';
type R={scale_ticket_no:string;member_phone:string;gross_weight_kg:number;moisture_pct:number;weigh_at:string;location_name:string;quality_grade:'A'|'B'|'C'}; type E={row:number;scale_ticket_no:string;reason:'member_not_found'|'duplicate_ticket'|'invalid_moisture'|'missing_field'|'location_not_found';detail:string};
const p=(csv:string)=>{const [h,...ls]=csv.trim().split(/\r?\n/);const k=h?.split(',').map(s=>s.trim())??[];return ls.filter(Boolean).map((l,i)=>{const v=l.split(',').map(s=>s.trim());const o:Record<string,string>={};k.forEach((x,j)=>o[x]=v[j]??'');return {i:i+2,o};});};
export async function POST(req:Request){const s=createServerSupabaseClient(); try{const ar=await requireAdminPermission('service.write'); if(isForbidden(ar)) return ar.forbidden; const q=new URL(req.url).searchParams.get('action'); const {csv}=await req.json() as {csv:string}; if(!csv) return NextResponse.json({error:'csv required'},{status:400});
const rows=p(csv), names=[...new Set(rows.map(r=>r.o.location_name).filter(Boolean))], tickets=[...new Set(rows.map(r=>r.o.scale_ticket_no).filter(Boolean))]; const [{data:locs},{data:dup}]=await Promise.all([s.from('pickup_locations').select('id,name').in('name',names), tickets.length?s.from('harvest_bookings').select('scale_ticket_no').in('scale_ticket_no',tickets):Promise.resolve({data:[]})]);
const lmap=new Map((locs??[]).map(l=>[String(l.name),String(l.id)])), dset=new Set((dup??[]).map(d=>String(d.scale_ticket_no))); const seen=new Set<string>(), valid:(R&{member_id:string;location_id:string})[]=[], errors:E[]=[];
for(const r of rows){const o=r.o,t=o.scale_ticket_no; if(!o.scale_ticket_no||!o.member_phone||!o.gross_weight_kg||!o.moisture_pct||!o.weigh_at||!o.location_name||!o.quality_grade) {errors.push({row:r.i,scale_ticket_no:t,reason:'missing_field',detail:'required fields missing'}); continue;} const m=Number(o.moisture_pct); if(!Number.isFinite(m)||m<0||m>100){errors.push({row:r.i,scale_ticket_no:t,reason:'invalid_moisture',detail:o.moisture_pct}); continue;} const lid=lmap.get(o.location_name); if(!lid){errors.push({row:r.i,scale_ticket_no:t,reason:'location_not_found',detail:o.location_name}); continue;} if(dset.has(t)||seen.has(t)){errors.push({row:r.i,scale_ticket_no:t,reason:'duplicate_ticket',detail:t}); continue;} const mid=await resolveMemberId(o.member_phone,s); if(!mid){errors.push({row:r.i,scale_ticket_no:t,reason:'member_not_found',detail:o.member_phone}); continue;} seen.add(t); valid.push({scale_ticket_no:t,member_phone:o.member_phone,gross_weight_kg:Number(o.gross_weight_kg),moisture_pct:m,weigh_at:o.weigh_at,location_name:o.location_name,quality_grade:(o.quality_grade as R['quality_grade']),member_id:mid,location_id:lid}); }
if(q==='preview') return NextResponse.json({ok:true,valid,errors}); if(q!=='commit') return NextResponse.json({error:'action must be preview|commit'},{status:400});
const dupeCheck=await s.from('harvest_bookings').select('scale_ticket_no').in('scale_ticket_no',valid.map(v=>v.scale_ticket_no)); if((dupeCheck.data??[]).length) return NextResponse.json({error:'duplicate ticket before commit',duplicates:dupeCheck.data},{status:409});
let committed=0; for(const v of valid){const w=new Date(v.weigh_at.replace(' ','T')); const b=await findOrCreateBooking(v.member_id,v.location_id,w,s); if(!b.found) continue; const r=await calculateIntake({gross_weight_kg:v.gross_weight_kg,moisture_pct:v.moisture_pct,member_id:v.member_id,location_id:v.location_id,weigh_at:w},s); await s.from('harvest_bookings').update({status:'completed',actual_completed_at:new Date().toISOString(),intake_source:'csv_import',intake_by:ar.admin.adminUserId,intake_location_id:v.location_id,scale_ticket_no:v.scale_ticket_no,quality_grade:v.quality_grade,gross_weight_kg:r.gross_weight_kg,deduct_pct:r.deduct_pct,net_weight_kg:r.net_weight_kg,actual_received_kg:r.net_weight_kg,actual_moisture_pct:v.moisture_pct,price_per_kg:r.final_price,bonus_per_kg:r.total_bonus,gross_amount:r.gross_amount,net_amount:r.net_amount}).eq('id',b.booking.id); committed++; const {data:m}=await s.from('members').select('line_uid').eq('id',v.member_id).maybeSingle(); if(m?.line_uid) void sendIntakeReceipt({lineUid:String(m.line_uid),result:r,bookingId:b.booking.id,scaleTicketNo:v.scale_ticket_no,locationName:v.location_name}).catch(()=>{}); }
return NextResponse.json({ok:true,committed,errors}); }catch(e){return NextResponse.json({error:String(e)},{status:500});}}
